### ISSUE TITLE
Allow only one song to play at a time

### ISSUE THREAD

**Issue by pradeepgangwar** [OrionStar25/Selena-Gomez-Discography#21]
Currently if we play more than one song they start playing together without pausing previous one. If we play next song, last one should be paused and only one should be allowed to play.

**Comment by LalitSharma7** [comment]
@openode claim

**Comment by Archies11** [comment]
Can I work on this?

**Comment by Rattlecode17sh** [comment]
@Archies you can take this issue i am working on some other project

**Comment by OrionStar25** [comment]
@Rattlecode17sh Assigned to you
