### ISSUE TITLE
Remove `toggle nav` in smaller screen sizes

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#26]
An unwanted `toggle nav` button is seen in smaller screen sizes. This needs to be removed without changing any functionality.

![screenshot from 2019-01-15 13-39-24](https://user-images.githubusercontent.com/28835849/51166930-18804d00-18cb-11e9-85ed-f9dafa72045d.png)

**Comment by Tarunasudani** [comment]
can I work on this..?

**Comment by OrionStar25** [comment]
Sure, go ahead!  @Tarunasudani

**Comment by Aswinpookkatt** [comment]
can i do this

**Comment by OrionStar25** [comment]
#23 This is solving this problem. And there isnt any update from you. Im closing this issue.
