### ISSUE TITLE
Music player comes out of the singles list on resizing

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#27]
![screenshot from 2019-01-15 13-41-53](https://user-images.githubusercontent.com/28835849/51167093-8cbaf080-18cb-11e9-802f-fab08b82cfdd.png)

Keep the width same as that of the list

**Comment by supremenishant** [comment]
Can i work on this?

**Comment by rishabhshuklax** [comment]
this is covered in issue #8

**Comment by OrionStar25** [comment]
Let this be a separate issue. @Firela you work on the feedbacks I gave you.
@supremenishant go ahead :+1:
