### ISSUE TITLE
Link "Creator" in navigation bar to profile

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#3]
When you click on `Creator` in navigation bar, this link should open: https://orionstar25.github.io/

**Comment by Archies11** [comment]
@OrionStar25 Can I work on this?

**Comment by Archies11** [comment]
I have deleted the comment on the other issue @OrionStar25

**Comment by shivam0211** [comment]
Can I work on this?
