### ISSUE TITLE
Add scroll in the dropdown of listen button

### ISSUE THREAD

**Issue by Rupeshiya** [OrionStar25/Selena-Gomez-Discography#33]
@OrionStar25 
It is looking weird to scroll full page for selecting any song after hovering listen button .

**Comment by batra-meghna** [comment]
@opencodebot claim

**Comment by ankichd11** [comment]
can i work on this?

**Comment by OrionStar25** [comment]
@batra-meghna assigned to you. @ankichd11 first finish your open PR or close it if you don't want to work on that issue.

**Comment by Rattlecode17sh** [comment]
Let me know if it is still open
