### ISSUE TITLE
Add a link of 'git help in creating a PR' to README.md

### ISSUE THREAD

**Issue by Divy123** [OrionStar25/Selena-Gomez-Discography#36]
This issue involves adding a link of github help page to creating a PR to README.md .
Step 1: Navigate to README.md file .
Step 2: Paste this link after adding an appropriate heading like :
### Creating a PR successfully
 https://help.github.com/articles/creating-a-pull-request/
Also go through markdown patterns to know how various headings and patterns are created.

I think this can be a good first-timer issue.

**Comment by Archies11** [comment]
Can I work on this?

**Comment by Divy123** [comment]
Sure @Archies11  go ahead..
