### ISSUE TITLE
Add pull request Template.

### ISSUE THREAD

**Issue by pradeepgangwar** [OrionStar25/Selena-Gomez-Discography#39]
Add a pull request template similar to [this](https://github.com/opencodeiiita/Opencode-Collaborative-19/pull/219/files). Remove the points which are not meant for this repository. For further instructions refer to [this](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

**Comment by sourabhpruthi10** [comment]
@pradeepgangwar @OrionStar25 i would like to work on this

**Comment by pradeepgangwar** [comment]
Yeah! Go ahead.
