### ISSUE TITLE
Make album tiles square

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#4]
Make the dimensions of album tiles equal and preferably into a square.
Make sure they remain responsive.

**Comment by ykatiyar** [comment]
Can I work on this?

**Comment by OrionStar25** [comment]
@nucelya Go ahead

**Comment by shivam0211** [comment]
Can I work on this?

**Comment by OrionStar25** [comment]
@shivam0211 This issue is taken, you will be assigned if no PR is given by @nucelya in 3 days

**Comment by OrionStar25** [comment]
@nucelya What's the status? @shivam0211 If you're interested, comment down.

**Comment by OrionStar25** [comment]
@nucelya Try to implement what I suggested you on slack. Then we will discuss more from there. :+1:
