### ISSUE TITLE
Album songs should overlap the album tiles on hover

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#42]
In mobile and Ipad view, albums names are currently hidden behind tiles. They should be above the tiles.

**Comment by sourabhpruthi10** [comment]
@OrionStar25 can i work on it.

**Comment by sourabhpruthi10** [comment]
can you provide me resources if needed so that i can solve the issue .

**Comment by vinaysomawat** [comment]
@OrionStar25 Can I work on it?

**Comment by OrionStar25** [comment]
Assigned to @sourabh1031 . Check [this](https://css-tricks.com/almanac/properties/z/z-index/) out.

**Comment by thenullterminator** [comment]
can i work on this ?

**Comment by SuneetKumar19** [comment]
can i work on this?

**Comment by OrionStar25** [comment]
@Archies11  assigned to you since @thenullterminator already has a PR open.
