### ISSUE TITLE
Add a movie section 

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#43]
We can add a horizontal movie section below the albums and singles list containing all the movies Selena has acted in.

Note: It doesn't need to be responsive.

**Comment by LalitSharma7** [comment]
Can i work on this issue i have completed my previous assigned task

**Comment by OrionStar25** [comment]
There are some minor changes left in that PR.

**Comment by LalitSharma7** [comment]
Completed that PR. Check it and let me know if i can work on this issue

**Comment by OrionStar25** [comment]
Sure, go ahead :)

**Comment by LalitSharma7** [comment]
Can you please tell me what details needs to be added in that section??

**Comment by OrionStar25** [comment]
All the movies she has worked in, in order of their release(newer first). 4 movies in a row should do.
