### ISSUE TITLE
Add section for providing live link in pull request template

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#48]

**Comment by vinaysomawat** [comment]
@OrionStar25 Can I work on this?

**Comment by vinaysomawat** [comment]
Also explain the issue properly!

**Comment by pradeepgangwar** [comment]
@vinaysomawat You have to change the .github/pull_request_template.md file and add a section where user can paste the live website link so that mentors can review changes.
