### ISSUE TITLE
Link song names to YouTube

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#5]
Some songs in specific albums have not yet been linked to YouTube.
Select **any one** album and correctly add YouTube links to the song.

**Comment by barney-stinson** [comment]
i wanna work

**Comment by niftyy** [comment]
i want to take this issue

**Comment by barney-stinson** [comment]
Can i work on this project?

**Comment by OrionStar25** [comment]
Comment the album you would be working on and start your PR :)

**Comment by barney-stinson** [comment]
stars dance
