### ISSUE TITLE
Make movie tiles round 

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#58]
Make the size of the movie tiles smaller and shape it round

**Comment by Archies11** [comment]
Can I work on this?

**Comment by OrionStar25** [comment]
@Archies11 update on other PR

**Comment by Archies11** [comment]
The previous PR is merged and closed, should I make these changes and update the previous itself?

**Comment by AshwiniMohan05** [comment]
I'm working on this.

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by SuneetKumar19** [comment]
@opencodebot claim

**Comment by Archies11** [comment]
@OrionStar25 is this issue still assigned to me?

**Comment by OrionStar25** [comment]
@Archies11 Ive assigned you a different issue.
@thenullterminator already has PR open for it.
