### ISSUE TITLE
Make movie tiles responsive

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#59]
Movie tiles are overlapping with singles list rn. Make it responsive for mobile and ipad view

**Comment by LalitSharma7** [comment]
@opencodebot claim

**Comment by OrionStar25** [comment]
@Rattlecode17sh  one at a time please. You have 2 PRs open already.

**Comment by LalitSharma7** [comment]
@OrionStar25 have a look at my previous PR and let me know if i can solve this one

**Comment by neerajd007** [comment]
@opencodebot claim

**Comment by LalitSharma7** [comment]
@OrionStar25 take a look at my PR and let me know if i can work on this issue

**Comment by OrionStar25** [comment]
@Rattlecode17sh Assigned!

**Comment by OrionStar25** [comment]
Re opening issue

**Comment by anupm12** [comment]
I will work on this
Can I?

**Comment by OrionStar25** [comment]
Sure go ahead! @anupm12

**Comment by OrionStar25** [comment]
Reopening for inactivity for 3 days.

**Comment by Archies11** [comment]
Can I work on it?

**Comment by OrionStar25** [comment]
Assigned to @Archies11 !
