### ISSUE TITLE
Update Singles' list

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#6]
Add all her new songs in the same order in the `Singles` list: **Newer first**

**Comment by barney-stinson** [comment]
Can I work on this?

**Comment by Archies11** [comment]
Can I work on this?

**Comment by LalitSharma7** [comment]
@opencodebot claim

**Comment by OrionStar25** [comment]
@barney-stinson Go ahead :+1:

**Comment by OrionStar25** [comment]
@barney-stinson  you've been assigned one already.

So @Rattlecode17sh  , you've been assigned this PR.

**Comment by OrionStar25** [comment]
@Rattlecode17sh What's the status? I'm unassigning you since its been 3 days.

**Comment by thenullterminator** [comment]
Can i work on this ?

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by OrionStar25** [comment]
@thenullterminator assigned to you!
