### ISSUE TITLE
Add correct soundtrack to songs in Singles list

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#7]
Choose **any 2 songs** of your choice from the `Singles` list which doesn't have the correct song and add the correct soundtrack for them.

The link doesn't need to change. You have to change the default song in the music player. Right now only one type of song is assigned to each player. Download the song and add it to the player.

**Comment by Archies11** [comment]
@OrionStar25 Can I work on this?

**Comment by barney-stinson** [comment]
@OrionStar25 Can I work on this?

**Comment by pradeepgangwar** [comment]
Please pick up one issue per repository and maximum 2 issues covering all projects of OpenCode at a time @Archies11 @barney-stinson. You guys have claimed other issues also.

**Comment by barney-stinson** [comment]
I've taken only one. Remaining two issues I've deleted. @pradeepgangwar

**Comment by Archies11** [comment]
I have deleted the other request.
@OrionStar25

**Comment by OrionStar25** [comment]
@Archies11 Go ahead. Pick the 1st 2 songs with the wrong track.

**Comment by barney-stinson** [comment]
I want to work on these-ONLY YOU & TRUST NOBODY @OrionStar25

**Comment by ankichd11** [comment]
can i work on this?

**Comment by OrionStar25** [comment]
@barney-stinson @ankichd11 , go ahead. Make sure to change the songs in the player. And don't choose the same songs. :laughing:

**Comment by barney-stinson** [comment]
I've choosen my songs

**Comment by Aswinpookkatt** [comment]
Can I work for this?

**Comment by Archies11** [comment]
Can I work on Fly to your heart and Shake it up?

**Comment by OrionStar25** [comment]
@Aswinpookkatt @Archies11  Go ahead!!

**Comment by sharmamansi** [comment]
CAN I WORK ON THIS

**Comment by OrionStar25** [comment]
@sharmamansi you can work on "bang a drum" and "magic" :)

**Comment by Archies11** [comment]
Can i work on the next two songs?

**Comment by OrionStar25** [comment]
@Archies11 sure, but make your PR title properly like : Add (song names)
`Update index.html` isn't an accepted PR title. :)

**Comment by brownsands** [comment]
Can i work on this!!

**Comment by OrionStar25** [comment]
Yes but mention the 2 songs here

**Comment by brownsands** [comment]
can i work on Everything Is Not What It Seems and Send It On!!

**Comment by OrionStar25** [comment]
@brownsands those are done, work on "New Classic" and "Trust in me"

**Comment by Tarunasudani** [comment]
can I work on this..?

**Comment by iit2018026** [comment]
can i work on this?

**Comment by OrionStar25** [comment]
All the songs have been assigned for now. :100:
