### ISSUE TITLE
Create a border for all images

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#70]
A black border around all the images in albums and movies will make it look more solid.

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by OrionStar25** [comment]
@thenullterminator finish your PR :P

**Comment by thenullterminator** [comment]
I THINK MY ROUND TILES PR IS MERGED

**Comment by OrionStar25** [comment]
Read the comments on it. I had to revert it.

**Comment by vishnuk7** [comment]
@opencode claim

**Comment by thenullterminator** [comment]
> Read the comments on it. I had to revert it.

I am not getting it can you please help....

**Comment by SuneetKumar19** [comment]
@OpenCode Can I this ??

**Comment by SuneetKumar19** [comment]
Can I work on this??

**Comment by HGOYAL015** [comment]
@OpenCode claim

**Comment by thenullterminator** [comment]
can i work on this as my previous pr is competed?

**Comment by SuneetKumar19** [comment]
Can I work on it??

**Comment by Rajat1999** [comment]
can I work on it?

**Comment by OrionStar25** [comment]
Reopening for inactivity

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by OrionStar25** [comment]
Assigned to @thenullterminator

**Comment by OrionStar25** [comment]
Also, make the edges of the album tiles round like you did before. Just add a `border-radius`, don't make any changes to its size.
