### ISSUE TITLE
Make the site responsive

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#8]
Make the `album tiles + Singles list` responsive for all screen sizes.

**Comment by rishabhshuklax** [comment]
Can I work on this?

**Comment by barney-stinson** [comment]
i wanna work on this

**Comment by barney-stinson** [comment]
Can I work on this?

**Comment by OrionStar25** [comment]
@Firela Yeah go ahead :+1:
