### ISSUE TITLE
Star and fork this repo for easy points!!

### ISSUE THREAD

**Issue by OrionStar25** [OrionStar25/Selena-Gomez-Discography#9]
Star the repo and fork it. Once done, comment **Done** below with a link to your fork and get easy points! :heart_eyes:

**Comment by Archies11** [comment]
Done: https://github.com/Archies11/Selena-Gomez-Discography

**Comment by LalitSharma7** [comment]
Done: https://github.com/Rattlecode17sh/Selena-Gomez-Discography

**Comment by sm-adil** [comment]
Done: https://github.com/mohammed-adil/Selena-Gomez-Discography

**Comment by neerajd007** [comment]
Done!
https://github.com/neerajd007/Selena-Gomez-Discography

**Comment by sourabhpruthi10** [comment]
Done: https://github.com/sourabh1031/Selena-Gomez-Discography

**Comment by shivam0211** [comment]
DONE!
https://github.com/shivam0211/Selena-Gomez-Discography

**Comment by SarthakSri98** [comment]
DONE!
https://github.com/SarthakSri98/Selena-Gomez-Discography

**Comment by barney-stinson** [comment]
**DONE**
https://github.com/barney-stinson/Selena-Gomez-Discography

**Comment by HumbleBustler** [comment]
DONE
https://github.com/HumbleBustler/Selena-Gomez-Discography

**Comment by Rkbp-099** [comment]
DONE
https://github.com/Rkbp-099/Selena-Gomez-Discography

**Comment by brownsands** [comment]
DONE
[https://github.com/brownsands/Selena-Gomez-Discography.git](url)

**Comment by amulyagaur** [comment]
DONE
https://github.com/amulyagaur/Selena-Gomez-Discography.git

**Comment by chiillax** [comment]
DONE : https://github.com/chiillax/Selena-Gomez-Discography.git

**Comment by girirajgo** [comment]
DONE: https://github.com/girirajgo/Selena-Gomez-Discography.git

**Comment by Kartik2301** [comment]
DONE: https://github.com/Kartik2301/Selena-Gomez-Discography

**Comment by tushparte** [comment]
DONE: https://github.com/niftyy/Selena-Gomez-Discography

**Comment by ashish4321** [comment]
DONE: https://github.com/ashish4321/Selena-Gomez-Discography

**Comment by rishabhshuklax** [comment]
Done!
https://github.com/Firela/Selena-Gomez-Discography

**Comment by supremenishant** [comment]
Done!! : https://github.com/supremenishant/Selena-Gomez-Discography,git

**Comment by supremenishant** [comment]
Done !! : https://github.com/supremenishant/Selena-Gomez-Discography.git

**Comment by iit2018026** [comment]
done
https://github.com/iit2018026/Selena-Gomez-Discography

**Comment by coderjolly** [comment]
done 
https://github.com/CoderJolly/Selena-Gomez-Discography

**Comment by bettercalln1ck** [comment]
DONE: https://github.com/nikolai6303/Selena-Gomez-Discography

**Comment by thenullterminator** [comment]
DONE:https://github.com/thenullterminator/Selena-Gomez-Discography

**Comment by mka2011** [comment]
done : https://github.com/mka2011/Selena-Gomez-Discography

**Comment by BLJS2warchief** [comment]
DONE!!!
https://github.com/BLJS2warchief/Selena-Gomez-Discography

**Comment by r00tDada** [comment]
DONE:https://github.com/r00tDada/Selena-Gomez-Discography

**Comment by thesmallstar** [comment]
done: https://github.com/thesmallstara/Selena-Gomez-Discography

**Comment by sa4k5hi** [comment]
Done: https://github.com/sa4k5hi/Selena-Gomez-Discography

**Comment by vinaysomawat** [comment]
Done: https://github.com/vinaysomawat/Selena-Gomez-Discography

**Comment by pal-0123** [comment]
DONE :https://github.com/pal-0123/Selena-Gomez-Discography

**Comment by msg12** [comment]
DONE:https://github.com/msg12/Selena-Gomez-Discography

**Comment by atreytushar11** [comment]
done
https://github.com/atreytushar11/Selena-Gomez-Discography

**Comment by deepakDOTexe** [comment]
Done : https://github.com/deepakDOTexe/Selena-Gomez-Discography

**Comment by devgupta2607** [comment]
Done : https://devgupta2607.github.io/Selena-Gomez-Discography/

**Comment by HGOYAL015** [comment]
**Done :**
 https://github.com/HGOYAL015/Selena-Gomez-Discography

**Comment by Rajat1999** [comment]
Done !!
Link : https://github.com/Rajat1999/Selena-Gomez-Discography

**Comment by anupm12** [comment]
Done
https://github.com/anupm12/Selena-Gomez-Discography

**Comment by ayanujju** [comment]
Done!
https://github.com/ayanujju/Selena-Gomez-Discography.git

**Comment by shivhek25** [comment]
Done !
https://github.com/shivhek25/Selena-Gomez-Discography

**Comment by kesari007** [comment]
Done 
https://github.com/kesari007/Selena-Gomez-Discography.git
